#!/usr/bin/env python3

import click
import digitalocean
import requests
from requests.adapters import HTTPAdapter
from requests.packages.urllib3.util.retry import Retry
import random
import string
import time
from eth_account import Account
from eth_utils.curried import keccak

DROPLET_BASE_NAME = "taraxa-node-oneclick"
DROPLET_SIZE = "c-4"
DROPLET_IMAGE = "ubuntu-20-04-x64"
DROPLET_USER_DATA_SCRIPT = "https://raw.githubusercontent.com/Taraxa-project/taraxa-ops/master/scripts/prepare/do.sh"
VOLUME_SIZE = 250

@click.group()
def cli():
    """DigitalOcean Testnet CLI"""
    pass


@cli.command()
@click.option('--nodes', default=1, help='Number of nodes')
@click.option('--project', default=None, help='Project name')
@click.option('--explorer-key', default=None, help='Explorer private key for delegation')
def create(nodes, project=None, explorer_key=None):
    if explorer_key is None:
        click.echo("The explorer key is required.")
        quit(1)

    manager = get_manager()

    check_auth(manager)
    project = check_project(manager, project)
    user_data = get_user_data()

    regions = get_regions(manager)

    droplets = []
    for i in range(0, nodes):
        name = ''.join(random.choice(string.ascii_letters) for x in range(6))
        region = random.choice(regions)

        volume_name = name.lower()
        volume = digitalocean.Volume(name=f'oneclick{volume_name}',
                                      region=region,
                                      size_gigabytes=VOLUME_SIZE)
        volume.create()
        volume.load()

        droplet = digitalocean.Droplet(name=f'{DROPLET_BASE_NAME}-{name}',
                                       region=region,
                                       image=DROPLET_IMAGE,
                                       size_slug=DROPLET_SIZE,
                                       volumes=[volume.id],
                                       user_data=user_data,
                                       backups=False)
        droplet.create()
        droplet.load()
        project.assign_resource([f'do:droplet:{droplet.id}'])

        droplets.append(droplet)

    click.echo('Waiting for droplets to start...')
    droplets = wait_for_droplets(droplets)

    click.echo('Checking droplets wallets...')
    wallets = {}
    while True:
        completed = []
        for droplet in droplets:
            droplet.load()

            try:
                response = requests.get(
                    f'http://{droplet.ip_address}:3000/api/address')
                if response.ok:
                    wallet_json = response.json()
                    wallet = wallet_json['value']
                    completed.append(wallet)
                    wallets[droplet.name] = wallet

                    account = Account.from_key(explorer_key)
                    sig = account.signHash(keccak(hexstr=wallet))
                    sig_hex = sig.signature.hex()

                    delegate_response = requests.get(
                        f'https://explorer.testnet.taraxa.io/api/delegate/0x{wallet}?sig={sig_hex}')

            except:
                click.echo(
                    f'Droplet {droplet.name} not ready yet')

            time.sleep(10)

        if len(completed) == len(droplets):
            break

    click.echo(wallets)


@cli.command()
def projects():
    manager = get_manager()

    check_auth(manager)
    projects = manager.get_all_projects()

    if len(projects) == 0:
        click.echo(f'No projects found.')
        quit(1)

    click.echo("{:<36} {:<30}".format('Id', 'Name'))
    for project in projects:
        click.echo("{:<36} {:<30}".format(project.id, project.name))


@cli.command()
@click.option('--project', default=None, help='Project name')
def delete(project):
    manager = get_manager()
    check_auth(manager)

    project = check_project(manager, project)
    resources = project.get_all_resources()

    droplets = []
    for resource in resources:
        if "do:droplet:" not in resource:
            continue

        droplet_id = resource.replace("do:droplet:", "")
        droplet = manager.get_droplet(droplet_id)

        if DROPLET_BASE_NAME not in droplet.name:
            continue

        droplets.append(droplet)

    if len(droplets) != 0:
        click.echo(f"Deleting droplets in {project.name}...")
        click.echo("{:<10} {:<30}".format('Id', 'Name'))
        for droplet in droplets:
            click.echo("{:<10} {:<30}".format(droplet.id, droplet.name))
            droplet.destroy()
    else:
        click.echo(f'No droplets found.')

    volumes = []
    for resource in resources:
        if "do:volume:" not in resource:
            continue

        volume_id = resource.replace("do:volume:", "")
        volume = manager.get_volume(volume_id)

        if "oneclick" not in volume.name:
            continue

        volumes.append(volume)

    if len(volumes) != 0:
        click.echo(f"Deleting volumes in {project.name}...")
        click.echo("{:<40} {:<30}".format('Id', 'Name'))
        for volume in volumes:
            click.echo("{:<40} {:<30}".format(volume.id, volume.name))
            volume.destroy()
    else:
        click.echo(f'No volumes found.')


def get_manager():
    manager = digitalocean.Manager()

    retry = Retry(connect=3)
    adapter = HTTPAdapter(max_retries=retry)
    manager._session.mount('https://', adapter)

    return manager


def check_auth(manager):
    try:
        manager.get_account()
    except:
        click.echo("Could not authenticate you.")
        click.echo(
            "Export the API key (DIGITALOCEAN_ACCESS_TOKEN=xxxx) before running the script.")
        quit(1)


def check_project(manager, project):
    projects = manager.get_all_projects()

    if project is None:
        project = manager.get_default_project()
    else:
        np = None
        for p in projects:
            if p.name == project:
                np = p
                break

        if np is None:
            click.echo(f'Project {project} not found.')
            quit(1)

        project = np
    return project


def get_regions(manager):
    regions = []
    for region in manager.get_all_regions():
        if DROPLET_SIZE in region.sizes:
            regions.append(region.slug)

    return regions


def get_user_data():
    user_data = None
    try:
        user_data = requests.get(DROPLET_USER_DATA_SCRIPT).text
    except:
        click.echo(
            f'Could not fetch user data script from {DROPLET_USER_DATA_SCRIPT}')
        quit(1)

    return user_data


def wait_for_droplets(droplets):
    while True:
        completed = []
        for droplet in droplets:
            actions = droplet.get_actions()
            for action in actions:
                action.load()
                if action.status == 'completed':
                    completed.append(droplet.id)

            time.sleep(1)

        if len(completed) == len(droplets):
            break
    return droplets


def wait_for_wallets():
    pass


if __name__ == '__main__':
    cli()
